#se especifican los dispositivos propios, tanto el router como el switch
#realizar esto permite tener una gestion con los dispositivos que se quieran automatizar
---
R18-Nelson:
  hostname: 192.168.100.121
  port: 33298
  platform: cisco_ios_telnet
  username: nelson
  password: "1234"
  groups:
  -   Nelson
  -   Routers
  data:
   secret: "1234" 

S19-Scarlett:
  hostname: 192.168.100.121
  port: 33299
  platform: cisco_ios_telnet
  username: scarlett
  password: br*v* 
  groups:
  -   Scarlett
  -   Switches
  data:
   secret: pucmm 
